os:
    - linux
language: generic
sudo: required
dist: trusty

before_install:
    - eval "$(curl -sL https://apt.vapor.sh)"
    - sudo apt-get install vapor
    - sudo chmod -R a+rx /usr/
    
    - git clone https://github.com/danger/danger-swift.git
    - cd danger-swift
    - swift build
    - cd ..
    # - npm install -g danger # This installs Danger
    # - brew install danger/tap/danger-swift # This installs Danger-Swift
    # - brew install swiftlint # This is for the Danger SwiftLint plugin.

script:
    - swift build
    - swift build -c release
    - swift test
    # - danger process danger-swift           # Run Danger

after_success:
    - eval "$(curl -sL https://swift.vapor.sh/codecov)"
