os:
    - linux
language: generic
sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang libblocksruntime0 libcurl4-openssl-dev

install:
  - sudo chmod -R a+rwx /usr/
  # - sudo chmod -R a+rwx /tmp/
  - node -v
  - npm install -g danger
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swiftenv global 4.0.3

  # - git clone https://github.com/realm/SwiftLint.git
  # - cd SwiftLint
  # - rm .swift-version
  # - swift build -c release --static-swift-stdlib
  # - mv .build/x86_64-unknown-linux/release/swiftlint /usr/local/bin/
  # - cd ..

  # - git clone https://github.com/petrpavlik/danger-swift.git
  # - cd danger-swift
  # - rm .swift-version
  # - make install
  # - cd ..
  
  - swift build 

script:
    - swift test
    # - export LINUX_SOURCEKIT_LIB_PATH=$HOME/usr/lib
    # - swiftlint lint --quiet --path "danger/Dangerfile.swift" --reporter json # test swiftlint
    # - danger process danger-swift           # Run Danger

    find / -name libsourcekitdInProc.so
